name: Sync Gentoo

on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hourss
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          base: master
          head: master
